name: Deploy to Azure
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AZURE
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Test login
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Create Resource Group (if not exists)
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group create --name ${{ vars.AZURE_RG }} --location eastus
      - name: Login in az AZ ACR
        run: az acr login --name ${{vars.AZURE_PREFIX}}acr
      - name: Build and push Node.js image
        run: |
          docker build -t ${{ vars.AZURE_PREFIX }}acr.azurecr.io/node-app:latest .
          docker push ${{ vars.AZURE_PREFIX }}acr.azurecr.io/node-app:latest

      - name: Deploy Node.js Container App
        run: |
          az containerapp revision copy \
            --name ${{ vars.AZURE_PREFIX }}containerapp \
            --resource-group ${{ vars.AZURE_RG }} \
            --image ${{ vars.AZURE_PREFIX }}acr.azurecr.io/node-app:latest \
            --cpu 1 \
            --memory 2Gi \

      - name: Configure Environment Variables for Node.js
        run: |
          az containerapp env update \
            --name ${{ vars.AZURE_PREFIX }}containerapp \
            --resource-group ${{ vars.AZURE_RG }} \
          --set-env-vars MONGODB_URI="mongodb://cads87containeradb:27017"
