  name: Deploy to Azure
  on:
    push:
      branches:
        - main

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Log in to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true

        - name: Build and deploy Container App
          uses: azure/container-apps-deploy-action@v1
          with:
            appSourcePath: ${{ github.workspace }}
            acrName: ${{ vars.AZURE_PREFIX }}acr
            resourceGroup: ${{ vars.AZURE_RG }}
            containerAppName: ${{ vars.AZURE_PREFIX }}containerapp
            containerAppEnvironment: ${{ vars.AZURE_PREFIX }}containerappenvironment
