name: Deploy to Azure
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AZURE
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Test login
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Create Resource Group (if not exists)
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group create --name ${{ vars.AZURE_RG }} --location eastus

      - name: Build and push MongoDB image
        run: |
          cd ${{ github.workspace }}/mongodb
          docker-compose build db
          docker tag $(docker-compose images -q db) ${{ vars.AZURE_PREFIX }}acr.azurecr.io/db:latest
          docker push ${{ vars.AZURE_PREFIX }}acr.azurecr.io/db:latest

      - name: Build and push Node.js app image
        run: |
          cd ${{ github.workspace }}
          docker-compose build app
          docker tag $(docker-compose images -q app) ${{ vars.AZURE_PREFIX }}acr.azurecr.io/app:latest
          docker push ${{ vars.AZURE_PREFIX }}acr.azurecr.io/app:latest

      - name: Deploy MongoDB Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/mongodb
          acrName: ${{ vars.AZURE_PREFIX }}acr
          resourceGroup: ${{ vars.AZURE_RG }}
          containerAppName: ${{ vars.AZURE_PREFIX }}containeradb
          containerAppEnvironment: ${{ vars.AZURE_PREFIX }}containerappenv
          location: eastus
          image: ${{ vars.AZURE_PREFIX }}acr.azurecr.io/db:latest

      - name: Deploy Node.js Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: ${{ vars.AZURE_PREFIX }}acr
          resourceGroup: ${{ vars.AZURE_RG }}
          containerAppName: ${{ vars.AZURE_PREFIX }}containerapp
          containerAppEnvironment: ${{ vars.AZURE_PREFIX }}containerappenv
          location: eastus
          image: ${{ vars.AZURE_PREFIX }}acr.azurecr.io/app:latest
