name: Deploy to Azure
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AZURE
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Test login
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: ${{ vars.AZURE_PREFIX }}acr
          resourceGroup: ${{ vars.AZURE_RG }}
          containerAppName: ${{ vars.AZURE_PREFIX }}containerapp
          containerAppEnvironment: ${{ vars.AZURE_PREFIX }}containerappenvironment
